-- MySQL Script generated by MySQL Workbench
-- Sat Oct 26 22:26:08 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_mp1
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_mp1` ;

-- -----------------------------------------------------
-- Schema db_mp1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_mp1` DEFAULT CHARACTER SET utf8 ;
USE `db_mp1` ;

-- -----------------------------------------------------
-- Table `db_mp1`.`tblActors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_mp1`.`tblActors` ;

CREATE TABLE IF NOT EXISTS `db_mp1`.`tblActors` (
  `lngActorID` INT NOT NULL AUTO_INCREMENT,
  `strActorFullName` VARCHAR(45) NULL,
  `memActorNotes` MEDIUMTEXT NULL,
  `picture` VARCHAR(45) NULL,
  PRIMARY KEY (`lngActorID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mp1`.`tblRoleTypes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_mp1`.`tblRoleTypes` ;

CREATE TABLE IF NOT EXISTS `db_mp1`.`tblRoleTypes` (
  `lngRoleTypeID` INT NOT NULL AUTO_INCREMENT,
  `strRoleType` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`lngRoleTypeID`),
  UNIQUE INDEX `lngRoleTypeID_UNIQUE` (`lngRoleTypeID` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mp1`.`tblFilmGenres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_mp1`.`tblFilmGenres` ;

CREATE TABLE IF NOT EXISTS `db_mp1`.`tblFilmGenres` (
  `lngGenreID` INT NOT NULL AUTO_INCREMENT,
  `strGenre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`lngGenreID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mp1`.`tblFilmCertificates`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_mp1`.`tblFilmCertificates` ;

CREATE TABLE IF NOT EXISTS `db_mp1`.`tblFilmCertificates` (
  `lngCertificateID` INT NOT NULL AUTO_INCREMENT,
  `strCertificate` VARCHAR(45) NULL,
  PRIMARY KEY (`lngCertificateID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mp1`.`tblFilmTitles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_mp1`.`tblFilmTitles` ;

CREATE TABLE IF NOT EXISTS `db_mp1`.`tblFilmTitles` (
  `lngFilmTitleID` INT NOT NULL AUTO_INCREMENT,
  `strFilmTitle` VARCHAR(45) NULL,
  `memFilmStory` MEDIUMTEXT NULL,
  `dtmFilmReleaseDate` DATE NULL,
  `intFilmDuration` INT NULL,
  `memFilmAdditionalInfo` MEDIUMTEXT NULL,
  `lngGenreID` INT NOT NULL,
  `lngCertificateID` INT NOT NULL,
  `picture` VARCHAR(45) NULL,
  PRIMARY KEY (`lngFilmTitleID`, `lngGenreID`, `lngCertificateID`),
  INDEX `fk_tblFilmTitles_tblFilmGenres1_idx` (`lngGenreID` ASC) ,
  INDEX `fk_tblFilmTitles_tblFilmCertificates1_idx` (`lngCertificateID` ASC) ,
  CONSTRAINT `fk_tblFilmTitles_tblFilmGenres1`
    FOREIGN KEY (`lngGenreID`)
    REFERENCES `db_mp1`.`tblFilmGenres` (`lngGenreID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tblFilmTitles_tblFilmCertificates1`
    FOREIGN KEY (`lngCertificateID`)
    REFERENCES `db_mp1`.`tblFilmCertificates` (`lngCertificateID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mp1`.`tblFilmsActorRoles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_mp1`.`tblFilmsActorRoles` ;

CREATE TABLE IF NOT EXISTS `db_mp1`.`tblFilmsActorRoles` (
  `strCharacterName` VARCHAR(45) NOT NULL,
  `memCharaterDescription` MEDIUMTEXT NULL,
  `lngActorID` INT NOT NULL,
  `lngRoleTypeID` INT NOT NULL,
  `lngFilmTitleID` INT NOT NULL,
  PRIMARY KEY (`lngActorID`, `lngRoleTypeID`, `lngFilmTitleID`),
  INDEX `fk_tblFilmsActorRoles_tblRoleTypes1_idx` (`lngRoleTypeID` ASC) ,
  INDEX `fk_tblFilmsActorRoles_tblFilmTitles1_idx` (`lngFilmTitleID` ASC) ,
  CONSTRAINT `fk_tblFilmsActorRoles_tblActors1`
    FOREIGN KEY (`lngActorID`)
    REFERENCES `db_mp1`.`tblActors` (`lngActorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tblFilmsActorRoles_tblRoleTypes1`
    FOREIGN KEY (`lngRoleTypeID`)
    REFERENCES `db_mp1`.`tblRoleTypes` (`lngRoleTypeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tblFilmsActorRoles_tblFilmTitles1`
    FOREIGN KEY (`lngFilmTitleID`)
    REFERENCES `db_mp1`.`tblFilmTitles` (`lngFilmTitleID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mp1`.`tblProducers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_mp1`.`tblProducers` ;

CREATE TABLE IF NOT EXISTS `db_mp1`.`tblProducers` (
  `lngProducerID` INT NOT NULL AUTO_INCREMENT,
  `strProducerName` VARCHAR(45) NULL,
  `hypContactEmailAddress` VARCHAR(45) NULL,
  `hypWebsite` VARCHAR(45) NULL,
  PRIMARY KEY (`lngProducerID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mp1`.`tblFilmTitlesProducers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_mp1`.`tblFilmTitlesProducers` ;

CREATE TABLE IF NOT EXISTS `db_mp1`.`tblFilmTitlesProducers` (
  `lngFilmTitleID` INT NOT NULL,
  `lngProducerID` INT NOT NULL,
  PRIMARY KEY (`lngFilmTitleID`, `lngProducerID`),
  INDEX `fk_tblFilmTitlesProducers_tblFilmTitles1_idx` (`lngFilmTitleID` ASC) ,
  INDEX `fk_tblFilmTitlesProducers_tblProducers1_idx` (`lngProducerID` ASC) ,
  CONSTRAINT `fk_tblFilmTitlesProducers_tblFilmTitles1`
    FOREIGN KEY (`lngFilmTitleID`)
    REFERENCES `db_mp1`.`tblFilmTitles` (`lngFilmTitleID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tblFilmTitlesProducers_tblProducers1`
    FOREIGN KEY (`lngProducerID`)
    REFERENCES `db_mp1`.`tblProducers` (`lngProducerID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mp1`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_mp1`.`user` ;

CREATE TABLE IF NOT EXISTS `db_mp1`.`user` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP);


-- -----------------------------------------------------
-- Table `db_mp1`.`tblUser`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_mp1`.`tblUser` ;

CREATE TABLE IF NOT EXISTS `db_mp1`.`tblUser` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
